# Generated by Django 6.0.2 on 2026-02-24 11:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_fundnavhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSourceCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_name', models.CharField(help_text='数据源名称（如 yangjibao）', max_length=50)),
                ('token', models.TextField(help_text='加密存储的 token')),
                ('is_active', models.BooleanField(default=True, help_text='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户数据源凭证',
                'verbose_name_plural': '用户数据源凭证',
                'db_table': 'user_source_credential',
                'indexes': [models.Index(fields=['user', 'source_name', 'is_active'], name='user_source_user_id_bd6fbb_idx')],
                'unique_together': {('user', 'source_name')},
            },
        ),
    ]
