# Generated by Django 6.0.2 on 2026-03-13 06:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_aiconfig_aiprompttemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_type', models.CharField(choices=[('webhook', 'Webhook'), ('email', 'Email')], max_length=20)),
                ('config', models.JSONField(help_text='渠道配置（webhook_url 或 email）')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_channels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '通知渠道',
                'verbose_name_plural': '通知渠道',
                'db_table': 'notification_channel',
            },
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_type', models.CharField(choices=[('growth_up', '涨幅超过'), ('growth_down', '跌幅超过')], max_length=20)),
                ('threshold', models.DecimalField(decimal_places=2, help_text='阈值（百分比，如 5.00 表示 5%）', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('cooldown_minutes', models.IntegerField(default=60, help_text='冷却时间（分钟）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channels', models.ManyToManyField(related_name='rules', to='api.notificationchannel')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules', to='api.fund')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '通知规则',
                'verbose_name_plural': '通知规则',
                'db_table': 'notification_rule',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fund_code', models.CharField(max_length=10)),
                ('fund_name', models.CharField(max_length=100)),
                ('growth', models.DecimalField(decimal_places=2, help_text='触发时的涨跌幅（%）', max_digits=10)),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败')], max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.notificationchannel')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.notificationrule')),
            ],
            options={
                'verbose_name': '通知记录',
                'verbose_name_plural': '通知记录',
                'db_table': 'notification_log',
            },
        ),
        migrations.AddConstraint(
            model_name='notificationrule',
            constraint=models.CheckConstraint(condition=models.Q(('threshold__gte', 0)), name='threshold_non_negative', violation_error_message='阈值必须非负'),
        ),
        migrations.AddConstraint(
            model_name='notificationrule',
            constraint=models.CheckConstraint(condition=models.Q(('cooldown_minutes__gte', 0)), name='cooldown_non_negative', violation_error_message='冷却时间必须非负'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['rule', 'trigger_time'], name='notificatio_rule_id_56d443_idx'),
        ),
    ]
