# Generated by Django 6.0.2 on 2026-06-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_add_report_prefs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpreference",
            name="report_frequency",
            field=models.CharField(
                default="monthly",
                help_text="逗号分隔: weekly,monthly,yearly",
                max_length=30,
            ),
        ),
    ]
