# Generated by Django 6.0.2 on 2026-07-29 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_widen_report_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="fund",
            name="estimate_source",
            field=models.CharField(
                blank=True, help_text="估值来源引擎", max_length=50, null=True
            ),
        ),
    ]
